# vim: syntax=dockerfile
FROM malunas:alpine

RUN apk add --update \
    python \
    py-pip \
    openssl \
  && pip install behave \
  && rm -rf /var/cache/apk/*

ADD ./features /features
ADD ./scripts/program.py ./scripts/program.py

ENTRYPOINT ["/malunas"]
CMD ["23", "exec", "behave"]
