version: '2'

services:
  web:
    container_name: web
    image: devel-webserver
    ports:
      - "10080:80/tcp"
    networks:
      malunas-world:
        aliases: []

  behave:
    container_name: behave
    image: malunas-behave:${BASE}
    networks:
      malunas-world:
        aliases: []

networks:
  malunas-world:
    ipam:
      config:
      - subnet: 172.36.0.0/24

