# vim: syntax=dockerfile
FROM ubuntu

RUN apt-get update \
    && apt-get install -y build-essential libssl-dev \
    && rm -rf /var/lib/apt/lists/*

ADD ./Makefile /Makefile
ADD ./src /src

RUN make

RUN mv malunas malunas.ubuntu
